# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.define "ubuntu" do |ubuntu|
    config.vm.box = "ubuntu/xenial64"
    config.vm.hostname = "cptdazarcv"
    # config.vm.provision "file", source: "scripts/vars.sh", destination: "/vagrant/vars.sh"
    config.vm.provision "shell", path: "scripts/azcmagent.connect.sh" 
    ubuntu.trigger.before :destroy do |trigger|
      trigger.warn = "Deleting Azure resource group"
      trigger.run_remote = {inline: "bash delete_rg.sh"}
    end
end

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    vb.name = "cptdazarcv"
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false 
  
    # Customize the amount of memory on the VM:
    vb.memory = "1024"   
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.
  
end
